name: teste
description: A new Flutter project.


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_speed_dial: ^6.2.0
  material_design_icons_flutter: ^6.0.7096
  http: ^0.13.5
  logger: ^1.1.0
  http_interceptor: ^1.0.2
  equatable: ^2.0.3
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  flutter_spinkit: ^5.1.0
  basic_utils: ^5.4.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:

 
  uses-material-design: true

  